# Generated by Django 5.1.5 on 2025-12-14 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='products.product'),
        ),
    ]
