from django.core.management.base import BaseCommand
from apps.catalog.models import Attribute, AttributeValue


class Command(BaseCommand):
    help = "Populate attributes and attribute values (including colors with hex codes)."

    def handle(self, *args, **kwargs):
        COLOR_HEX_CODES = {
            "Red": "#FF0000",
            "Blue": "#0000FF",
            "Green": "#008000",
            "Yellow": "#FFFF00",
            "Black": "#000000",
            "White": "#FFFFFF",
            "Purple": "#800080",
            "Orange": "#FFA500",
            "Pink": "#FFC0CB",
            "Brown": "#A52A2A",
            "Gray": "#808080",
            "Vanilla": "#F3E5AB",
            "Chocolate": "#D2691E",
            "Strawberry": "#FC5A8D",
            "Lemon": "#FFF700",
            "Lime": "#00FF00",
            "Raspberry": "#E30B5C",
            "Blueberry": "#4F86F7",
            "Cherry": "#C20021",
            "Grape": "#6F2DA8",
            "Watermelon": "#FC6C85",
            "Coconut": "#E0E0E0",
            "Pineapple": "#FFDF00",
            "Mango": "#FFB347",
            "Apple": "#FF0800",
            "Banana": "#FFE135",
            "Peppermint": "#AAF0D1",
            "Cinnamon": "#A1866F",
            "Coffee": "#6F4E37",
            "Hazelnut": "#CD853F",
            "Almond": "#EFDECD",
            "Caramel": "#C68E17",
            "Maple": "#B5651D",
            "Honey": "#FFC30B",
            "Mint": "#98FF98",
            "Ginger": "#B06500",
            "Lavender": "#E6E6FA",
            "Rose": "#FF007F",
            "Bubblegum": "#FFC1CC",
            "Coral": "#FF7F50",
            "Cyan": "#00FFFF",
            "Turquoise": "#40E0D0",
            "Sage": "#B2AC88",
            "Seafoam": "#9FE2BF",
            "Teal": "#008080",
            "Gold": "#FFD700",
            "Silver": "#C0C0C0",
            "Bronze": "#CD7F32",
            "Cream": "#FFFDD0",
            "Beige": "#F5F5DC",
            "Taupe": "#483C32",
            "Mocha": "#3B2F2F",
            "Khaki": "#F0E68C",
            "Olive": "#808000",
            "Sand": "#C2B280",
            "Ivory": "#FFFFF0",
            "Crimson": "#DC143C",
            "Cerise": "#DE3163",
            "Fuchsia": "#FF00FF",
            "Lilac": "#C8A2C8",
            "Magenta": "#FF00FF",
            "Maroon": "#800000",
            "Navy": "#000080",
            "Periwinkle": "#CCCCFF",
            "Plum": "#DDA0DD",
            "Puce": "#CC8899",
            "Rust": "#B7410E",
            "Sienna": "#A0522D",
            "Tangerine": "#F28500",
            "Cobalt": "#0047AB",
            "Cerulean": "#007BA7",
            "Azure": "#007FFF",
            "Royal": "#4169E1",
            "Steel": "#4682B4",
            "Slate": "#708090",
            "Charcoal": "#36454F",
            "Ebony": "#555D50",
            "Raven": "#141414",
            "Midnight": "#191970",
            "Onyx": "#353839",
            "Jet": "#343434",
            "Ink": "#22333B",
        }

        data = {
            "Color": list(COLOR_HEX_CODES.keys()),
            "Size": [
                "Small",
                "Medium",
                "Large",
                "XL",
                "XXL",
                "XXXL",
                "4XL",
                "5XL",
                "6XL",
                "xsmall",
                "Extra Small",
                "Extra Extra Small",
                "One Size",
                "Free Size",
                "Short",
                "Regular",
                "Long",
                "Extra Long",
            ],
            "Material": [
                "Cotton",
                "Polyester",
                "Leather",
                "Metal",
                "Plastic",
                "Wood",
                "Glass",
                "Ceramic",
                "Silk",
                "Nylon",
                "Wool",
                "Paper",
                "Fabric",
                "Rubber",
                "Bamboo",
                "Stainless Steel",
                "Aluminum",
                "Brass",
                "Copper",
                "Iron",
                "Bronze",
                "Kevlar",
                "Carbon Fiber",
                "Acrylic",
                "Polycarbonate",
                "Fiberglass",
                "Linen",
                "Rayon",
                "Spandex",
                "Hemp",
                "Cashmere",
                "Velvet",
                "Denim",
                "Lace",
                "Satin",
                "Fleece",
            ],
            "Voltage": ["110V", "220V", "240V", "12V", "24V", "48V"],
            "Wattage": ["100W", "200W", "300W", "500W", "64W"],
            "PlugType": ["Type A", "Type B", "Type C", "Type D", "Type E", "Type F"],
            "Weight": [
                "0.1 KG",
                "0.5 KG",
                "1 KG",
                "1.5 KG",
                "2 KG",
                "2.5 KG",
                "3 KG",
                "4 KG",
                "5 KG",
                "6 KG",
                "7 KG",
                "8 KG",
                "9 KG",
                "10 KG",
                "12 KG",
                "15 KG",
                "16 KG",
                "18 KG",
                "20 KG",
                "22 KG",
                "24 KG",
                "25 KG",
                "26 KG",
                "28 KG",
                "30 KG",
                "32 KG",
                "34 KG",
                "36 KG",
                "38 KG",
                "40 KG",
                "42 KG",
                "44 KG",
                "46 KG",
                "48 KG",
                "50 KG",
            ],
            "Dimensions": [
                "10x10x10 cm",
                "20x20x20 cm",
                "30x30x30 cm",
                "50x50x50 cm",
            ],
            "OperatingSystem": [
                "Windows",
                "macOS",
                "Linux",
                "Android",
                "iOS",
                "Chrome OS",
                "Ubuntu",
                "Fedora",
                "Debian",
                "CentOS",
                "Red Hat",
                "SUSE",
                "openSUSE",
                "Lubuntu",
                "Kubuntu",
                "Xubuntu",
                "Arch Linux",
                "Gentoo",
                "Slackware",
                "FreeBSD",
                "NetBSD",
                "OpenBSD",
                "Haiku",
                "ReactOS",
            ],
            "Capacity": ["256GB", "512GB", "1TB", "2TB", "4TB"],
            "Resolution": ["720p", "1080p", "4K", "8K"],
            "Speed": ["1 GHz", "1.9 GHz", "2.0 GHz", "2.4 GHz", "3.0 GHz", "4.0 GHz"],
            "Style": [
                "Casual",
                "Formal",
                "Sporty",
                "Vintage",
                "Bohemian",
                "Minimalist",
                "Classic",
                "Trendy",
            ],
            "Pattern": [
                "Solid",
                "Striped",
                "Floral",
                "Checkered",
                "Polka Dot",
                "Geometric",
                "Animal Print",
                "Plaid",
            ],
            "CPU": [
                "Intel Core i3",
                "Intel Core i5",
                "Intel Core i7",
                "Intel Core i9",
                "Intel Pentium",
                "Intel Celeron",
                "Intel Xeon",
                "Intel Core 2 Duo",
                "Intel Core 2 Quad",
                "Intel Dual-Core Xeon",
                "AMD Ryzen 3",
                "AMD Ryzen 5",
                "AMD Ryzen 7",
                "AMD Ryzen 9",
                "AMD EPYC",
                "AMD Opteron",
                "AMD Phenom",
                "AMD Phenom II",
                "AMD Athlon",
                "AMD FX",
                "AMD Sempron",
                "AMD Turion",
                "ARM Cortex-A53",
                "ARM Cortex-A57",
                "ARM Cortex-A72",
                "ARM Cortex-A73",
                "ARM Cortex-A75",
                "ARM Cortex-A76",
                "ARM Cortex-A77",
                "ARM Cortex-A78",
                "ARM Mali-T860",
                "ARM Mali-T830",
                "ARM Mali-T820",
                "ARM Mali-T810",
                "ARM Mali-T860MP2",
                "ARM Mali-T860MP4",
                "ARM Mali-T830MP2",
                "ARM Mali-T830MP4",
                "ARM Mali-T820MP2",
                "ARM Mali-T820MP4",
                "ARM Mali-T810MP2",
                "ARM Mali-T810MP4",
            ],
            "Storage Capacity": [
                "3GB",
                "2GB",
                "4GB",
                "8GB",
                "16GB",
                "32GB",
                "64GB",
                "128GB",
            ],
            "RAM Capacity": ["2GB", "4GB", "8GB", "16GB", "32GB", "64GB", "128GB"],
            "Connectivity": [
                "Bluetooth",
                "Wi-Fi",
                "Ethernet",
                "USB",
                "NFC",
                "Cellular",
                "GPS",
            ],
            "Screen Size": [
                "13 inches",
                "15 inches",
                "17 inches",
                "24 inches",
                "27 inches",
                "32 inches",
            ],
            "Battery Life": ["3 hours", "5 hours", "8 hours", "10 hours", "12 hours"],
            "Camera Resolution": ["5MP", "8MP", "12MP", "16MP", "20MP"],
            "Brand": [
                "Apple",
                "Samsung",
                "Google",
                "Microsoft",
                "Sony",
                "LG",
                "Dell",
                "HP",
                "Asus",
                "Acer",
                "Lenovo",
            ],
            "Condition": ["New", "Used", "Refurbished"],
            "Features": [
                "Waterproof",
                "Dustproof",
                "Shockproof",
                "Fingerprint sensor",
                "Face recognition",
                "Voice assistant",
                "Noise cancellation",
            ],
        }

        for attribute_name, values in data.items():
            attribute, created = Attribute.objects.get_or_create(name=attribute_name)
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f"Attribute '{attribute_name}' added.")
                )

            for value in values:
                if attribute_name == "Color":
                    color_code = COLOR_HEX_CODES.get(value)
                    attr_value, created = AttributeValue.objects.get_or_create(
                        attribute=attribute,
                        value_name=value,
                        defaults={"color_code": color_code},
                    )
                    if not created and not attr_value.color_code:
                        attr_value.color_code = color_code
                        attr_value.save(update_fields=["color_code"])
                        self.stdout.write(
                            self.style.SUCCESS(
                                f"Value '{attr_value.value_name}' for attribute '{attribute_name}' updated with color code."
                            )
                        )
                else:
                    attr_value, created = AttributeValue.objects.get_or_create(
                        attribute=attribute, value_name=value
                    )

                if created:
                    self.stdout.write(
                        self.style.SUCCESS(
                            f"Value '{attr_value.value_name}' for attribute '{attribute_name}' added."
                        )
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING(
                            f"Value '{attr_value.value_name}' for attribute '{attribute_name}' already exists."
                        )
                    )
