from django.core.management.base import BaseCommand
from apps.catalog.models import Category, SubCategory


class Command(BaseCommand):
    help = "Populate categories and subcategories."

    def handle(self, *args, **options):
        categories_and_subcategories = {
            "Networking and Connectivity": {
                "Modems",
                "Wi-Fi Extenders",
                "Routers",
                "Switches",
                "Network Accessories",
                "Cables",
            },
            "Computing and Peripherals": {
                "Laptops",
                "Desktop Computers",
                "Monitors",
                "Keyboards and Mice",
                "Printers",
                "USB Cables",
                "Chargers",
                "Adapters",
                "HDMI Cables",
                "Power Banks",
                "Cable Management Accessories",
            },
            "Home Appliances": {
                "Refrigerators",
                "Washing Machines",
                "Microwaves",
                "Dishwashers",
                "Air Conditioners",
            },
            "Health and Fitness": {
                "Exercise and Physical Activity",
                "Nutrition",
                "Mental Health and Mindfulness",
                "Disease Prevention and Management",
                "Sports and Athletics",
                "Wellness and Holistic Health",
                "Weight Management",
                "Fitness Equipment and Gear",
                "Health Education and Coaching",
                "Community and Social Fitness",
                "Recovery and Rehabilitation",
            },
            "Photography": {
                "Cameras",
                "Lenses",
                "Camera Accessories",
                "Lighting Equipment",
                "Photography Studio Gear",
                "Camera Supports and Stabilizers",
                "Memory Cards and Storage",
                "Camera Cleaning and Maintenance",
                "Photography Software",
                "Photography Books and Education",
                "Camera Drones and Accessories",
                "Camera and Lens Care",
                "Photography Apparel",
                "Camera Accessories for Smartphone Photography",
            },
            "Electronic Components and Parts": {
                "Screens and Displays",
                "Semiconductors",
                "Capacitors",
                "Resistors",
            },
            "Tools": {
                "Hand Tools",
                "Power Tools",
                "Cutting Tools",
                "Measuring and Layout Tools",
                "Fastening Tools",
                "Woodworking Tools",
                "Metalworking Tools",
                "Gardening and Landscaping Tools",
                "Automotive Tools",
                "Construction and Masonry Tools",
                "Plumbing Tools",
                "Electrical Tools",
                "Painting and Decorating Tools",
                "Masonry and Tile Tools",
                "Automotive Repair Tools",
                "Welding and Soldering Tools",
            },
            "Clothing and Apparel": {
                "Tops",
                "Bottoms",
                "Outerwear",
                "Dresses",
                "Activewear",
                "Swimwear",
                "Intimate Apparel",
                "Footwear",
                "Accessories",
                "Formalwear",
                "Uniforms",
                "Maternity Wear",
                "Kids' and Baby Clothing",
                "Costumes and Cosplay",
                "Specialty Clothing",
                "Ethnic and Cultural Clothing",
                "Vintage and Retro Clothing",
                "Sustainable and Eco-Friendly Clothing",
            },
            "Electricals": {
                "Home Appliances",
                "Small Kitchen Appliances",
                "Entertainment Electronics",
                "Computing and Office Electronics",
                "Smart Home Devices",
                "Batteries and Power Sources",
                "Electrical Wiring and Components",
                "Security Systems",
                "Industrial and Commercial Electrical Equipment",
                "Automotive Electricals",
                "Electrical Safety Equipment",
            },
            "Stationery": {
                "Pens",
                "Pencils",
                "Erasers",
                "Notebooks and Notepads",
                "Paper",
                "Folders and Binders",
                "Clips and Fasteners",
                "Adhesives",
                "Scissors and Cutting Tools",
                "Desk Accessories",
                "Calendars and Planners",
                "Stamps and Stamp Pads",
                "Envelopes",
                "Presentation Supplies",
                "Office Tools",
                "Art Supplies",
                "Craft Supplies",
                "Filing and Storage",
            },
            "Mobile Phones and Accessories": {
                "Smartphones",
                "Feature Phones",
                "Refurbished Phones",
                "Unlocked Phones",
                "Basic Phones",
                "Gaming Phones",
                "Rugged Phones",
                "Mobile Phone Cases and Covers",
                "Screen Protectors",
                "Mobile Phone Chargers and Cables",
                "Bluetooth Headsets and Earbuds",
                "Mobile Phone Batteries",
                "Mobile Phone Holders and Mounts",
                "Car Accessories for Mobile Phones",
                "Mobile Phone Signal Boosters",
                "Mobile Phone Repair Parts",
            },
            "Speakers and Sounds": {
                "Bluetooth Speakers",
                "Home Speakers",
                "Computer Speakers",
                "Studio Monitors",
                "Soundbars",
                "Outdoor Speakers",
                "Wireless Speakers",
                "Portable Speakers",
                "Subwoofers",
                "Bookshelf Speakers",
                "Surround Sound Speakers",
                "Car Speakers",
            },
            "Sports and Outdoor Equipment": {
                "Baseball and Softball Equipment",
                "Bicycles and Accessories",
                "Camping and Hiking Gear",
                "Cycling",
                "Fitness and Exercise Equipment",
                "Football Equipment",
                "Golf Equipment",
                "Hockey Equipment",
                "Lacrosse Equipment",
                "Racquet Sports Equipment",
                "Soccer Equipment",
                "Swimming and Diving Equipment",
                "Tennis Equipment",
                "Track and Field Equipment",
                "Volleyball Equipment",
            },
            "Toys and Games": {
                "Action Figures and Accessories",
                "Art and Craft Supplies",
                "Baby and Preschool Toys",
                "Building and Construction Toys",
                "Collectible Toys",
                "Dolls and Accessories",
                "Educational and Learning Toys",
                "Electronic Toys",
                "Games and Puzzles",
                "Imaginative Play Toys",
                "Outdoor Toys and Games",
                "Pretend Play Toys",
                "Ride-On Toys",
                "Toy Building Sets",
                "Toy Vehicles",
            },
            "Gaming and VR": {
                "Console Accessories",
                "Gaming Controllers",
                "Gaming Desks and Chairs",
                "Gaming Keyboards and Mice",
                "Gaming Laptops",
                "Gaming Monitors",
                "Gaming PCs and Consoles",
                "Gaming Software",
                "Gaming Sound Cards and Speakers",
                "Gaming Virtual Reality (VR) and Augmented Reality (AR)",
                "Gaming Webcams",
            },
            "Furniture and Interior Design": {
                "Living Room Furniture",
                "Bedroom Furniture",
                "Office Furniture",
                "Storage Solutions",
                "Lighting",
                "Decor",
            },
        }

        for category_name, subcategories in categories_and_subcategories.items():
            category, created = Category.objects.get_or_create(name=category_name)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Category '{category_name}' added."))
            for sub_name in subcategories:
                subcategory, sub_created = SubCategory.objects.get_or_create(
                    category=category, sub_category_name=sub_name
                )
                if sub_created:
                    self.stdout.write(
                        self.style.SUCCESS(f"Subcategory '{sub_name}' added to '{category_name}'.")
                    )

