# Generated by Django 5.1.5 on 2025-12-14 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'gift_cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_column='Code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('discounttype', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], db_column='DiscountType', max_length=11)),
                ('value', models.DecimalField(db_column='Value', decimal_places=2, max_digits=10)),
                ('validfrom', models.DateField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateField(blank=True, db_column='ValidTo', null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('unique_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'discounts',
                'managed': True,
            },
        ),
    ]
