# Generated by Django 5.1.5 on 2026-05-10 10:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_subcategory_category'),
        ('products', '0003_alter_product_variation_theme'),
        ('promotions', '0002_initial'),
        ('sellers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Promo Attempt',
                'verbose_name_plural': 'Promo Attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['code', 'attempted_at'], name='promotions__code_92c379_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='promotions__ip_addr_e86c0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(help_text="Internal name e.g. 'Summer 2026 Campaign'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shown to customer on successful apply')),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off (%)'), ('fixed_amount', 'Fixed Amount Off (GHS)'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y Free'), ('fixed_price', 'Fixed Cart Price')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0–100) for PERCENTAGE. Amount for FIXED_AMOUNT. 0 for FREE_SHIPPING / BUY_X_GET_Y / FIXED_PRICE.', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap a percentage discount (e.g. 20% off but never more than GHS 50).', max_digits=10, null=True)),
                ('buy_quantity', models.PositiveSmallIntegerField(default=0, help_text='BUY_X_GET_Y: qty to buy')),
                ('get_quantity', models.PositiveSmallIntegerField(default=0, help_text='BUY_X_GET_Y: qty given free')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='FIXED_PRICE: total cart price after discount.', max_digits=10, null=True)),
                ('target_type', models.CharField(choices=[('entire_order', 'Entire Order'), ('products', 'Specific Products'), ('categories', 'Specific Categories'), ('seller_products', "All of seller's products")], default='entire_order', max_length=20)),
                ('include_free_shipping', models.BooleanField(default=False, help_text='When true, free shipping is also applied regardless of discount_type.')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart subtotal before this code can be applied.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_items_count', models.PositiveSmallIntegerField(default=0, help_text='Minimum number of items in cart.')),
                ('user_segment', models.CharField(choices=[('all', 'All Customers'), ('new', 'New Customers Only (first order)'), ('returning', 'Returning Customers'), ('logged_in', 'Logged-in Users Only'), ('specific', 'Specific User IDs')], default='all', max_length=15)),
                ('stackable', models.BooleanField(default=False, help_text='Can this code be combined with other promos on the same order?')),
                ('first_order_only', models.BooleanField(default=False, help_text='Shortcut for user_segment = NEW.')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Global cap. Leave blank for unlimited.', null=True)),
                ('max_redemptions_per_user', models.PositiveSmallIntegerField(default=1, help_text='Per-user cap. 0 = unlimited.')),
                ('current_redemptions', models.PositiveIntegerField(default=0, editable=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Apply automatically when conditions are met — no code entry required.')),
                ('auto_apply_priority', models.PositiveSmallIntegerField(default=0, help_text='If multiple auto-apply codes qualify, higher priority wins.')),
                ('categories', models.ManyToManyField(blank=True, related_name='promos', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promos', to='products.product')),
                ('seller', models.ForeignKey(blank=True, help_text="Leave blank for a platform-wide promo (ops / marketing). Set to a SellerProfile to scope this promo to that seller's products only.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='sellers.sellerprofile')),
                ('specific_users', models.ManyToManyField(blank=True, help_text='Only relevant when user_segment = SPECIFIC.', related_name='assigned_promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(db_index=True, help_text='Order ID (UUID or int as string).', max_length=64)),
                ('session_key', models.CharField(blank=True, help_text='For guest checkouts.', max_length=64)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_type_snap', models.CharField(max_length=20)),
                ('discount_value_snap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Redemption',
                'verbose_name_plural': 'Promo Redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('reward_type', models.CharField(choices=[('discount', 'Discount on next order'), ('points', 'Loyalty points'), ('credit', 'Store credit')], default='discount', max_length=20)),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_promo', models.ForeignKey(blank=True, help_text='The promo applied to the NEW user who uses this referral.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='promotions.promocode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promotions__code_2587f5_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promotions__is_acti_657bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['seller', 'is_active'], name='promotions__seller__650cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo', 'user'], name='promotions__promo_i_f15fa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promoredemption',
            unique_together={('promo', 'order_id')},
        ),
    ]
