# Generated by Django 5.1.5 on 2026-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promoattempt_promocode_promoredemption_referralcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('max_seller_discount_percentage', models.PositiveSmallIntegerField(default=50, help_text='Hard cap on the % a seller can offer in any single code (1-100).')),
                ('max_seller_codes_per_month', models.PositiveSmallIntegerField(default=20, help_text='Per-seller cap on how many new codes can be created in a calendar month. 0 = unlimited.')),
                ('seller_max_redemptions_cap', models.PositiveIntegerField(blank=True, help_text="Optional ceiling on a seller code's max_redemptions (protect against runaway promos). Blank = no cap.", null=True)),
                ('commission_basis', models.CharField(choices=[('pre_discount', 'Pre-discount (Amazon — platform takes % on original price)'), ('post_discount', 'Post-discount (Etsy — platform takes % on what customer paid)')], default='pre_discount', help_text='PRE_DISCOUNT: platform commission is calculated on the pre-discount price; the seller absorbs the full discount. POST_DISCOUNT: commission is on what the customer actually paid; platform shares the discount cost.', max_length=20)),
                ('allow_seller_platform_stacking', models.BooleanField(default=False, help_text='When OFF (default): a seller code and a platform code cannot be applied to the same order — validation rejects the second one. Per-code opt-in via the existing `stackable` flag overrides this.')),
                ('public_storefront_codes_visible', models.BooleanField(default=True, help_text="If True, a seller's active promo codes are visible on their public storefront page.")),
            ],
            options={
                'verbose_name': 'Promo Policy',
                'verbose_name_plural': 'Promo Policies',
            },
        ),
    ]
