# Generated by Django 5.1.5 on 2026-04-29 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFlowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('identifier_kind', models.CharField(max_length=16)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('password_reset', 'Password reset')], max_length=32)),
                ('step', models.CharField(choices=[('identified', 'Identified'), ('otp_sent', 'OTP sent'), ('otp_verified', 'OTP verified'), ('completed', 'Completed')], default='identified', max_length=32)),
                ('otp_hash', models.CharField(blank=True, max_length=256)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_max_attempts', models.IntegerField(default=5)),
                ('otp_resend_count', models.IntegerField(default=0)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_flow_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_flow_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'purpose'], name='auth_flow_s_identif_26c193_idx'), models.Index(fields=['expires_at'], name='auth_flow_s_expires_1e3f37_idx')],
            },
        ),
    ]
