# Generated by Django 5.1.5 on 2026-05-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_subcategory_category'),
        ('products', '0003_alter_product_variation_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('section_type', models.CharField(choices=[('horizontal_scroll', 'Horizontal Scroll'), ('grid', 'Product Grid'), ('flash_sale', 'Flash Sale (with countdown)'), ('banner', 'Promotional Banner'), ('category_spotlight', 'Category Spotlight')], default='horizontal_scroll', max_length=30)),
                ('max_products', models.PositiveSmallIntegerField(default=12)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.CharField(choices=[('manual', 'Manual (hand-picked)'), ('auto', 'Automatic (rule-based)'), ('mixed', 'Mixed (pinned + auto fill)')], default='auto', max_length=10)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('show_countdown', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('top_sellers', 'Top Sellers'), ('new_arrivals', 'New Arrivals'), ('high_rated', 'Highest Rated'), ('flash_sale', 'Flash Sale Products'), ('tag_filter', 'Products with Tag (keywords)'), ('category_best', 'Best in Category'), ('low_stock', 'Low Stock (urgency)'), ('trending', 'Trending (recent views)'), ('manual_override', 'Disabled (manual only)')], default='top_sellers', max_length=20)),
                ('lookback_days', models.PositiveSmallIntegerField(default=7, help_text='TOP_SELLERS / TRENDING / CATEGORY_BEST: window in days (trending converts to hours × 24).')),
                ('min_rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('tag', models.CharField(blank=True, help_text='TAG_FILTER: matched against product keywords (contains).', max_length=100)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=10)),
                ('only_in_stock', models.BooleanField(default=True)),
                ('only_available', models.BooleanField(default=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cache_minutes', models.PositiveSmallIntegerField(default=30)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='merchandising.homepagesection')),
            ],
            options={
                'verbose_name': 'Population Rule',
                'verbose_name_plural': 'Population Rules',
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('label_override', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_appearances', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandising.homepagesection')),
            ],
            options={
                'verbose_name': 'Section Product',
                'verbose_name_plural': 'Section Products',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('section', 'product'), name='merch_unique_section_product')],
            },
        ),
        migrations.CreateModel(
            name='SectionClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(db_index=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='merchandising.homepagesection')),
            ],
            options={
                'verbose_name': 'Section Click',
                'verbose_name_plural': 'Section Clicks',
                'indexes': [models.Index(fields=['section', 'clicked_at'], name='merchandisi_section_5a0173_idx')],
            },
        ),
    ]
