# Generated by Django 5.1.5 on 2025-12-14 23:31

import apps.products.models
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_in_stock', models.IntegerField()),
                ('restock_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturername', models.CharField(db_column='ManufacturerName', max_length=255)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('contactperson', models.CharField(blank=True, db_column='ContactPerson', max_length=100, null=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('engagement_time', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_start', models.DateTimeField()),
                ('discount_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_discounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('image_type', models.CharField(choices=[('main', 'Main Image'), ('supplementary', 'Supplementary Image'), ('infographic', 'Infographic Image')], default='supplementary', max_length=20)),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['-is_main', 'created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductKeyFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_keyfeatures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('min_buy_amount', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_variants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'purchase_histories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Archived', 'Archived'), ('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Published', 'Published'), ('Suspended', 'Suspended')], db_column='status', max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.CharField(db_column='Keywords', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('main_product_image', models.ImageField(blank=True, null=True, upload_to='main_product_images/')),
                ('min_amount', models.IntegerField(default=1, null=True)),
                ('thin', models.CharField(blank=True, db_column='THIN', default=apps.products.models.get_thin, max_length=100, null=True, unique=True)),
                ('inventory_level', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Refurbished', 'Refurbished')], db_column='condition', max_length=255, null=True)),
                ('variation_theme', models.CharField(choices=[('single', 'Single Product'), ('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('pattern', 'Pattern'), ('style', 'Style'), ('capacity', 'Capacity'), ('memory', 'Memory'), ('size-color', 'Size & Color'), ('size-material', 'Size & Material'), ('color-style', 'Color & Style'), ('size-pattern', 'Size & Pattern'), ('size-style', 'Size & Style'), ('size-color-style', 'Size, Color & Style'), ('RAM Capacity-memory', 'RAM Capacity & Memory'), ('custom', 'Custom')], default='single', max_length=20)),
                ('is_spare_part', models.BooleanField(default=False)),
                ('requires_installation', models.BooleanField(default=False)),
                ('is_product_of_the_month', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
