# Generated by Django 5.1.5 on 2026-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation_theme',
            field=models.CharField(choices=[('single', 'Single Product'), ('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('pattern', 'Pattern'), ('style', 'Style'), ('capacity', 'Capacity'), ('memory', 'Memory'), ('size-color', 'Size & Color'), ('size-material', 'Size & Material'), ('color-style', 'Color & Style'), ('size-pattern', 'Size & Pattern'), ('size-style', 'Size & Style'), ('size-color-style', 'Size, Color & Style'), ('RAM Capacity-memory', 'RAM Capacity & Memory'), ('custom', 'Custom'), ('all', 'All variants (flat list)')], default='single', max_length=20),
        ),
    ]
