# Generated by Django 5.1.5 on 2026-05-09 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_subcategory_category'),
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('banner', 'Banner (image strip)'), ('carousel', 'Carousel (multi-image)'), ('modal', 'Modal / popup'), ('topbar', 'Top bar (sticky strip)'), ('sidebar', 'Sidebar'), ('inline_card', 'Inline card'), ('fullscreen', 'Fullscreen overlay')], default='banner', max_length=20)),
                ('aspect_ratio', models.CharField(blank=True, help_text="e.g. '16/9', '1/1', '21/9'. Hint to creative producers.", max_length=20)),
                ('max_active_slots', models.PositiveSmallIntegerField(default=1, help_text='Hard cap on how many ad slots will return for this placement at once. Use >1 for carousels.')),
                ('rotation_seconds', models.PositiveSmallIntegerField(default=0, help_text='If >0 and max_active_slots>1, FE rotates creatives every N seconds.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('advertiser', models.CharField(blank=True, help_text='Internal label, brand, or seller running the campaign.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (5, 'Normal'), (10, 'High'), (20, 'Urgent (always wins)')], default=5, help_text='Higher priority campaigns get a multiplier in the auction.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('daily_impression_cap', models.PositiveIntegerField(blank=True, help_text='Pause this campaign for the day after N impressions across all creatives.', null=True)),
                ('total_impression_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('seller', models.ForeignKey(blank=True, help_text='Optional — if this campaign was paid for by a seller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('format', models.CharField(choices=[('image', 'Single image'), ('video', 'Video'), ('html', 'Custom HTML'), ('text', 'Text-only')], default='image', max_length=10)),
                ('image_desktop', models.ImageField(blank=True, null=True, upload_to='ads/creatives/desktop/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Optional. Falls back to desktop if missing.', null=True, upload_to='ads/creatives/mobile/')),
                ('video_url', models.URLField(blank=True)),
                ('html_body', models.TextField(blank=True, help_text='Sanitized HTML for HTML creatives.')),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('subheadline', models.CharField(blank=True, max_length=240)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above headline.', max_length=60)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.URLField(blank=True, max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='Selection weight. Higher = more likely. 0 disables the slot.')),
                ('position_hint', models.PositiveSmallIntegerField(default=0, help_text='For carousels: ordering within the placement.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('dismissible', models.BooleanField(default=True, help_text='If True, FE renders a close button. Stored per-session in localStorage.')),
                ('show_close_after_seconds', models.PositiveSmallIntegerField(default=0, help_text='Modals only — delay before close button appears.')),
                ('delay_seconds', models.PositiveSmallIntegerField(default=0, help_text='Modals only — show after N seconds on page.')),
                ('cap_per_session', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited.')),
                ('cap_per_day', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited.')),
                ('cap_per_week', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited.')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ads.adplacement')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ads.creative')),
            ],
            options={
                'ordering': ['placement_id', 'position_hint', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO-3166 alpha-2 codes. Empty = all countries. e.g. ["GH","NG","KE"].')),
                ('exclude_countries', models.JSONField(blank=True, default=list)),
                ('devices', models.JSONField(blank=True, default=list, help_text='Subset of ["mobile","tablet","desktop"]. Empty = all.')),
                ('user_states', models.JSONField(blank=True, default=list, help_text='Subset of UserState values. Empty = any.')),
                ('languages', models.JSONField(blank=True, default=list, help_text='ISO 639-1 codes, e.g. ["en","fr"]. Empty = all.')),
                ('min_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('only_with_empty_cart', models.BooleanField(default=False)),
                ('path_includes', models.JSONField(blank=True, default=list, help_text='Show only when current path contains any of these substrings.')),
                ('path_excludes', models.JSONField(blank=True, default=list)),
                ('ab_bucket', models.CharField(blank=True, help_text="Optional — limit to one A/B bucket (e.g. 'A', 'B').", max_length=20)),
                ('categories', models.ManyToManyField(blank=True, help_text='Show only on pages within these categories. Empty = all.', related_name='ad_targeting_rules', to='catalog.category')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targeting', to='ads.adslot')),
            ],
            options={
                'verbose_name': 'Targeting Rule',
                'verbose_name_plural': 'Targeting Rules',
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creative_id', models.UUIDField(db_index=True)),
                ('placement_id', models.BigIntegerField(db_index=True)),
                ('campaign_id', models.UUIDField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('served_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adslot')),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'indexes': [models.Index(fields=['campaign_id', 'served_at'], name='ads_adimpre_campaig_076354_idx'), models.Index(fields=['placement_id', 'served_at'], name='ads_adimpre_placeme_82c175_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creative_id', models.UUIDField(db_index=True)),
                ('placement_id', models.BigIntegerField(db_index=True)),
                ('campaign_id', models.UUIDField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('destination_url', models.CharField(blank=True, max_length=500)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adslot')),
            ],
            options={
                'verbose_name': 'Ad Click',
                'verbose_name_plural': 'Ad Clicks',
                'indexes': [models.Index(fields=['campaign_id', 'clicked_at'], name='ads_adclick_campaig_5ce25e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='ads_campaig_status_7bdd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='adslot',
            index=models.Index(fields=['placement', 'is_active'], name='ads_adslot_placeme_865669_idx'),
        ),
        migrations.AddIndex(
            model_name='adslot',
            index=models.Index(fields=['starts_at', 'ends_at'], name='ads_adslot_starts__8f770a_idx'),
        ),
    ]
