# Generated by Django 5.1.5 on 2026-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='background_color',
            field=models.CharField(blank=True, help_text="Hex (#a43d00) or full CSS background value (e.g. 'linear-gradient(...)').", max_length=200),
        ),
    ]
