# Generated by Django 5.1.5 on 2025-12-14 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['user', 'is_verified'], name='seller_prof_user_id_a3eb79_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['store_slug'], name='seller_prof_store_s_00c918_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['verification_status'], name='seller_prof_verific_b44370_idx'),
        ),
    ]
